version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: tr_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus-config.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: tr_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./dashbord_grafana_node_export.json:/var/lib/grafana/dashboards/dashbord_grafana_node_export.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set the admin password
    depends_on:
      - prometheus  # Ensure Prometheus starts before Grafana

  
  node_exporter:
    image: prom/node-exporter
    container_name: tr_node_exporter
    ports:
      - "9100:9100"

volumes:
  grafana-storage:
    driver: local