version: '3.8'

services:
  alertmanager:
    image: prom/alertmanager
    container_name: tr_alertmanager
    env_file:
      - ./.env
    ports:
      - "9093:9093"
    volumes:
      - ./provisioning/alertmanager:/etc/alertmanager/
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yaml"
  prometheus:
    image: prom/prometheus
    container_name: tr_prometheus
    depends_on:
      - alertmanager
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./shared_volumes/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
  grafana:
    image: grafana/grafana
    container_name: tr_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    env_file:
      - ./.env
    depends_on:
      - prometheus  # Ensure Prometheus starts before Grafana
  node_exporter:
    image: prom/node-exporter
    container_name: tr_node_exporter
    ports:
      - "9100:9100"
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: ping_pong_user
  #     POSTGRES_USER: thesheriff
  #     POSTGRES_PASSWORD: test123
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  # web:
  #   build: ./database/db
  #   volumes:
  #     - ./database/db:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./.env
  #   command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]


volumes:
  postgres_data:
  # prometheus_data:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: /Users/rdragan/Lab/ft_transcendence/volumes/shared_volumes/prometheus