version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ping_pong_user
      POSTGRES_USER: thesheriff
      POSTGRES_PASSWORD: test123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=ping_pong_user
      - DATABASE_USER=thesheriff
      - DATABASE_PASSWORD=test123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  postgres_data: