# Generated by Django 5.1.1 on 2024-09-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_x', models.FloatField(default=0.5)),
                ('ball_y', models.FloatField(default=0.5)),
                ('ball_speed_x', models.FloatField(default=0.009)),
                ('ball_speed_y', models.FloatField(default=0.009)),
                ('paddle1_y', models.FloatField(default=0.5)),
                ('paddle2_y', models.FloatField(default=0.5)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('game_state', models.CharField(choices=[('WA', 'Waiting'), ('PL', 'Playing')], default='WA', max_length=2)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
