# Generated by Django 5.1.1 on 2024-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline'), ('RE', 'Ready'), ('PL', 'Playing')], default='OF', max_length=2),
        ),
    ]
