# Generated by Django 5.1.1 on 2024-09-24 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_gameroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='pong.userprofile'),
        ),
    ]
