# Generated by Django 5.1.1 on 2024-09-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_alter_gameroom_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='state',
            field=models.CharField(choices=[('WA', 'Waiting'), ('PL', 'Playing')], default='WA', max_length=2),
        ),
    ]
