# Generated by Django 5.1.1 on 2024-09-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_alter_gameroom_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_game', to='pong.gameroom'),
        ),
        migrations.AlterField(
            model_name='ponggame',
            name='game_state',
            field=models.CharField(choices=[('WA', 'Waiting'), ('PL', 'Playing'), ('FI', 'Finished')], default='WA', max_length=2),
        ),
    ]
