# Generated by Django 5.1.1 on 2024-10-04 08:55

import django.db.models.deletion
import django.utils.timezone
import pong.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_ponggame_room_alter_ponggame_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponggame',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='pong.userprofile', validators=[pong.models.validate_players_different]),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='state',
            field=models.CharField(choices=[('WA', 'Waiting'), ('FL', 'Full')], default='WA', max_length=2),
        ),
    ]
