# Generated by Django 5.0.6 on 2024-10-13 18:27

from django.db import migrations


class Migration(migrations.Migration):
    def create_ai_user(apps, schema_editor):
        # Get tables
        User = apps.get_model('auth', 'User')
        UserProfile = apps.get_model('pong', 'UserProfile')

        # Check if the AI user already exists
        if not User.objects.filter(username='game_ai').exists():
            User.objects.create_user(
                username='game_ai',
                email='ai@game.com',
                password='super_secure_ai_password'
            )
        
        # Make user not login-able
        ai_user = User.objects.get(username='game_ai')
        ai_user.is_active = False
        ai_user.save()

        # Create the UserProfile for the AI user
        UserProfile.objects.create(
            user=ai_user,
            games_played=0,
            games_won=0,
        )


    dependencies = [
        ('pong', '0010_gameroom_isaiplay'),
    ]

    operations = [
        migrations.RunPython(create_ai_user),
    ]
