# Generated by Django 5.0.6 on 2024-08-28 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avarage', models.IntegerField(default=0)),
                ('longestStreak', models.IntegerField(default=0)),
                ('allPoints', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_app.user')),
            ],
        ),
    ]
