# Generated by Django 5.0.6 on 2024-08-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('player1_position', models.FloatField(default=0.5)),
                ('player2_position', models.FloatField(default=0.5)),
                ('ball_x', models.FloatField(default=0.5)),
                ('ball_y', models.FloatField(default=0.5)),
                ('ball_dx', models.FloatField(default=0.01)),
                ('ball_dy', models.FloatField(default=0.01)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
