# Generated by Django 5.0.6 on 2024-07-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_tablematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablematch',
            name='position_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablematch',
            name='position_player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablematch',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablematch',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
