# Generated by Django 5.0.6 on 2024-09-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_rename_nickname_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lost',
        ),
        migrations.RemoveField(
            model_name='user',
            name='won',
        ),
    ]
