# Generated by Django 5.0.6 on 2024-08-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_usermetrics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMetrics',
            new_name='UserMetric',
        ),
    ]
