# Generated by Django 5.0.6 on 2024-09-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_remove_user_lost_remove_user_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
