# Generated by Django 5.0.6 on 2024-10-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_rename_nickname_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='set_password',
        ),
    ]
