# Generated by Django 5.0.6 on 2024-10-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_rename_password_user_set_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='set_password',
            new_name='password',
        ),
    ]
