# Generated by Django 5.0.6 on 2024-10-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_rename_set_password_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
