# Generated by Django 5.0.6 on 2024-10-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_delete_tablematch'),
        ('backend_app', '0012_gameroom_ponggame'),
    ]

    operations = [
    ]
