# Generated by Django 4.2.16 on 2024-11-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0013_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatar/default.png', null=True, upload_to='avatar/'),
        ),
    ]
