# Generated by Django 4.2.16 on 2024-11-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0013_tictacroom'),
        ('backend_app', '0014_alter_user_avatar'),
    ]

    operations = [
    ]
