# Generated by Django 4.2.16 on 2024-11-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0013_merge_0012_delete_tablematch_0012_gameroom_ponggame'),
        ('backend_app', '0017_user_friends'),
    ]

    operations = [
    ]
