# Generated by Django 4.2.16 on 2024-11-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0018_merge_20241104_1558'),
        ('backend_app', '0018_user_display_name'),
    ]

    operations = [
    ]
