# Generated by Django 4.2.16 on 2024-11-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0020_aigameroom_tablematch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIGameRoom',
        ),
    ]
