# Generated by Django 4.2.16 on 2024-11-05 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0022_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='state',
            field=models.CharField(choices=[('WA', 'Waiting'), ('FL', 'Full'), ('FI', 'Finished')], default='WA', max_length=2),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_tournament', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3_tournament', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4_tournament', to=settings.AUTH_USER_MODEL),
        ),
    ]
