# Generated by Django 4.2.16 on 2024-11-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0023_tournament_state_alter_tournament_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_rooms', to='backend_app.tournament'),
        ),
    ]
