# Generated by Django 4.2.16 on 2024-11-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0024_gameroom_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
