# Generated by Django 4.2.16 on 2024-11-08 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0025_remove_gameroom_tournament_delete_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictacgame',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_tictac', to=settings.AUTH_USER_MODEL),
        ),
    ]
