# Generated by Django 4.2.16 on 2024-11-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0026_alter_tictacgame_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictacgame',
            name='second_player_typed_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
