# Generated by Django 4.2.16 on 2024-11-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0027_tictacgame_second_player_typed_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableMatch',
        ),
    ]
